<a href="https://colab.research.google.com/github/lauraemmanuella/IntroducaoPython/blob/main/8_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 

https://numpy.org/doc/stable/user/absolute_beginners.html

Numpy é uma biblioteca de álgebra linear para Python, a razão pela qual é tão importante para a ciência de dados em Python é que quase todas as bibliotecas dependem do Numpy como um dos seus **principais blocos de construção**.

O NumPy oferece várias maneiras rápidas e eficientes de **criar matrizes e manipular dados numéricos dentro delas**.

Os arrays NumPy são mais rápidos e compactos do que as listas Python. Isso permite que o código seja otimizado ainda mais. Veja mais em: https://stackoverflow.com/questions/993984/what-are-the-advantages-of-numpy-over-regular-python-lists

* Permite a criação de arrays homogêneos
* Pode ser criado a partir de uma lista ou tupla do python ou pode ser criado usando seus próprios métodos 

In [ ]:
#Importar biblioteca usando alias
import numpy as np

## Numpy Arrays

Numpy arrays essencialmente vêm de duas formas: vetores (1D) e matrizes (2D). Para arrays 3D ou dimensões superiores, o termo **tensor** é comumente usado.

### Criando Numpy Arrays

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [ ]:
minha_lista = [1,2,3]

In [ ]:
vetor = np.array(minha_lista)

In [ ]:
type(vetor)

numpy.ndarray

In [ ]:
print(vetor)

[1 2 3]


In [ ]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
matriz = np.array(minha_matriz)

In [ ]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(matriz)

numpy.ndarray

### Tipos dos elementos

Os elementos do array numpy são do mesmo tipo (estrutura homogênea)

In [ ]:
mlista = [12.5, 'laura', 35, True]
print(mlista)

[12.5, 'laura', 35, True]


In [ ]:
type(mlista[3])

bool

In [ ]:
marray = np.array(mlista)

In [ ]:
print(marray)

['12.5' 'laura' '35' 'True']


In [ ]:
type(marray[1])

numpy.str_

In [ ]:
type(marray)

numpy.ndarray

## Métodos incorporados (Built-in Methods)

Há muitas maneiras embutidas de gerar numpy arrays

### arange

Retorna valores uniformemente espaçados dentro de um determinado intervalo.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros e ones

Gerar matrizes de zeros ou de uns

In [ ]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [ ]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [ ]:
np.ones(3)

array([ 1.,  1.,  1.])

In [ ]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Retorna números uniformemente espaçados ao longo de um intervalo especificado.

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Cria uma matriz identidade

In [ ]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Random 

Numpy também tem muitas maneiras de criar arrays de números aleatórios:

### rand
Cria uma matriz da forma dada e preencha com amostras aleatórias de uma distribuição uniforme sobre ``[0, 1)``.

In [ ]:
np.random.rand()

0.32228143267490916

In [ ]:
np.random.rand(2)

array([0.92244399, 0.57038821])

In [ ]:
np.random.rand(2)*10

array([5.66522554, 8.30381741])

In [ ]:
np.random.rand(5,5)*100

array([[76.38262903, 72.80343653, 65.32996195, 52.70226626, 93.49923195],
       [28.97721363, 13.27490874, 18.3827809 ,  0.92965991, 22.81080497],
       [71.10362694, 49.5181699 , 63.74847165, 41.23408302, 91.21646871],
       [98.87794431, 15.9524222 ,  4.04710948, 53.57445986, 48.17664556],
       [63.51374909,  9.94202148,  4.72474696, 26.26108597, 78.81812338]])

### randint
Retorna inteiros aleatórios de "low" (inclusive) para "high" (not inclusive).

In [ ]:
np.random.randint(5) #entre 0 e 4

3

In [ ]:
np.random.randint(1,5,10) #entre 1 e 4, 10 elementos

array([1, 1, 3, 2, 3, 3, 4, 4, 4, 2])

In [ ]:
np.random.randint(1,5, size=(2, 4)) #entre 1 e 4, matriz 2X4

array([[4, 4, 3, 2],
       [4, 1, 1, 4]])

### Reshape
Retorna uma matriz contendo os mesmos dados com uma nova forma.

In [ ]:
arr = np.arange(12)

In [ ]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
arr2 = arr.reshape(4,3) #dados organizados em 4 linhas e 3 colunas

In [ ]:
print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos, ou para encontrar seus locais de índice usando argmin ou argmax

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
print(ranarr)

[45 30 19 45 17 24  2 41 27 27]


In [ ]:
ranarr.max()

45

In [ ]:
ranarr.argmax()

0

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

6

## Shape

Shape é um atributo que os arrays têm que retorna a dimensão do array

In [ ]:
arr2.shape #dimensão do array

(4, 3)

In [ ]:
arr2.shape[0] #quantidade de linhas

4

In [ ]:
arr2.shape[1] #quantidade de colunas

3

## Indexação
A maneira mais simples de escolher um ou alguns elementos de uma matriz é muito semelhante às listas de python:

In [ ]:
# Obtendo um valor através de um índice
arr[8]

8

In [ ]:
# Obtendo valores em um intervalo
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

### Indexação de matrizes

No caso de matrizes, pode-se usar duplo colchetes ou um colchete separando as dimensões por vírgula

In [ ]:
mat = np.random.rand(4,3)

In [ ]:
mat

array([[0.19687293, 0.65658506, 0.02326513],
       [0.30122861, 0.47815334, 0.54234024],
       [0.10872215, 0.81224061, 0.03720702],
       [0.61428829, 0.43218426, 0.17600331]])

In [ ]:
mat[0,0]

0.19687293108587633

In [ ]:
mat[0:3, 0:2] #define intervalo das linhas e intervalo das colunas

array([[0.19687293, 0.65658506],
       [0.30122861, 0.47815334],
       [0.10872215, 0.81224061]])

In [ ]:
mat.shape

(4, 3)

## Transmissão

Pode-se aplicar um valor ou operação a todo o array ou parte dele

In [ ]:
# Configurando um valor com intervalo de índice (Transmissão)
arr[0:5]=100

#Show
print(arr)

[100 100 100 100 100   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]


In [ ]:
# Notas importantes sobre fatias
slice_de_arr = arr[0:6]

# Mostra a fatia
print(slice_de_arr)

[100 100 100 100 100   5]


In [ ]:
# Modifica a fatia
slice_de_arr[:]=99

#Show Slice again
slice_de_arr

array([99, 99, 99, 99, 99, 99])

Agora note que as mudanças também ocorrem no array original!

In [ ]:
print(arr)

[99 99 99 99 99 99  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


Os dados não são copiados, é uma visão do array original! Isso evita problemas de memória!

In [ ]:
# Para obter uma cópia, precisa ser explícito
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Seleção condicional

Vamos examinar brevemente como usar colchetes para seleção com base em operadores de comparação.

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arrMaiorQuatro = arr[arr > 4]

In [ ]:
print(arrMaiorQuatro)

[ 5  6  7  8  9 10]
